### ISSUE TITLE
Missing Images

### ISSUE THREAD

**Issue by JulieKuehl** [wptrainingteam/how-to-find-help-with-wordpress#2]
- [x] Wordpress.org Support image

- [x] WordPress Codex

**Comment by pbrocks** [comment]
Links on the wayback machine
[Archived Page for Lesson Plan](https://web.archive.org/web/20150913003910/https://make.wordpress.org/training/handbook/user-lessons/how-to-find-help-with-wordpress/)
[wordpress.org_support.jpg](https://web.archive.org/web/20151027113542/https://make.wordpress.org/training/files/2014/12/wordpress.org_support.jpg)

**Comment by JulieKuehl** [comment]
images found and updated thanks to @pbrocks great idea!!!
